# Generated by Django 5.2.13 on 2026-04-30 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0265_usercontactinfo_ui_use_tailwind'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='authorized_users',
            field=models.ManyToManyField(blank=True, related_name='authorized_products', to='dojo.dojo_user'),
        ),
        migrations.AddField(
            model_name='product_type',
            name='authorized_users',
            field=models.ManyToManyField(blank=True, related_name='authorized_product_types', to='dojo.dojo_user'),
        ),
    ]
